export const shopTypes = {
    FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',

    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
    FETCH_SUBMENU_SUCCESS: 'FETCH_SUBMENU_SUCCESS',
    FETCH_BRANDS_SUCCESS: 'FETCH_BRANDS_SUCCESS',

    FETCH_PRODUCTS_ERROR: 'FETCH_PRODUCTS_ERROR'
}